######################
#        modbus      #
######################
CC=gcc
TARGET=SIMPLECLIENT
TARGET:test.c
	gcc -g test.c -o SIMPLECLIENT -lmodbus -lpthread 
clean:
	rm -f SIMPLECLIENT SIMPLECLIENT.o
